# Use Node image for development
FROM oven/bun:latest

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN bun install --frozen-lockfile

# Set host to allow external connections
ENV VITE_HOST=0.0.0.0

# Expose Vite's port
EXPOSE 5173

# Start development server
CMD ["bun", "--bun", "run", "dev", "--", "--host"]